config/routes.rb
Webl::Application.routes.draw do
	

	root :to => 'posts#index'
	match '/about' => 'static#about'
	match '/signout' => 'sessions#destroy', :as => :sign_out
	match '/signin' => 'sessions#new', :as => :sign_in

  match "/auth/:provider/callback" => "sessions#create_from_github"
  match "/auth/failure" => "sessions#failure_from_github"
	resources :sessions, 	:only => [:new, :create, :destroy] do
	  get 'new_from_github', :on => :collection
  end
	resources :users, 		:only => [:show, :new, :create, :edit, :update] do
		resources :posts, :only => :index
	end
  resources :posts do
		resources :comments, :except => [:index, :show, :new]
		get 'search', :on => :collection
	end
	resources :tags, :only => [:index, :show]
	
	namespace :admin do
		resources :users do
			put 'ban', :on => :member
		end
		resources :posts, :only => [:index, :destroy]
		resources :comments, :only => [:index, :edit, :update, :destroy]
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  attr_accessible :content, :user_id, :post_id, :as => :admin

	default_scope includes(:user)

	validates :content, :presence => true
	validates :user_id, :post_id, :presence => true
	validate :user_id_should_be_valid, :post_id_should_be_valid

	belongs_to :post, :counter_cache => true
	belongs_to :user
	
	private 
	
		def user_id_should_be_valid
			errors.add(:user_id, "should be a valid user") if user.nil?
		end
	
		def post_id_should_be_valid
			errors.add(:post_id, "should be a valid post") if post.nil?
		end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
	load_resource :except => :index
	
  def index
		@comments = Comment.order("created_at DESC").paginate(:page => params[:page])
  end

  def edit
  end

	def update
		if @comment.update_attributes(params[:comment], :as => :admin)
			flash[:success] = "Comment updated."
			redirect_to admin_comments_path
		else
			flash.now[:error] = "Oops! There was an error updating this comment."
			render 'edit'
		end
	end

  def destroy
		@comment.destroy
		redirect_to admin_comments_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :post
  load_and_authorize_resource :comment, :through => :post

  def create
    if @comment.save
      redirect_to @post, :notice => "Successfully created comment."
    else
      flash[:error] = "Comment could not be saved"
			redirect_to @post
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(params[:comment])
      redirect_to @post, :notice  => "Successfully updated comment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to @post, :notice => "Successfully destroyed comment."
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/edit.html.haml
- title "Edit comment"

= form_for [:admin, @comment] do |f|
	%table.form
		%tr
			%td{colspan:2}
				= f.error_messages
		%tr
			%td= f.label :content
			%td= f.text_area :content, :class => :xxlarge, :rows => 5
		%tr
			%td= f.label :user
			%td= collection_select(:comment, :user_id, User.all, :id, :name, {:prompt => false})
		%tr
			%td= f.label :post
			%td= collection_select(:comment, :post_id, Post.all, :id, :title, {:prompt => false})
		%tr
			%td
			%td= f.submit

app/views/admin/comments/index.html.haml
-title "Recent Comments"

%table
	%tr
		%th Recent comments
	-for comment in @comments
		%tr
			%td
				%p 
					=link_to comment.user.name.humanize, admin_user_path(comment.user)
					|
					=link_to comment.post.title, post_path(comment.post)
					%span.right=comment.created_at
				%p= comment.content
				%p
					= link_to "edit", edit_admin_comment_path(comment)
					|
					= link_to "destroy",  admin_comment_path(comment), :method => :delete, :confirm => "Are you sure you want to delete this comment?"
					
= will_paginate @comments