config/routes.rb
Webl::Application.routes.draw do
	

	root :to => 'posts#index'
	match '/about' => 'static#about'
	match '/signout' => 'sessions#destroy', :as => :sign_out
	match '/signin' => 'sessions#new', :as => :sign_in

  match "/auth/:provider/callback" => "sessions#create_from_github"
  match "/auth/failure" => "sessions#failure_from_github"
	resources :sessions, 	:only => [:new, :create, :destroy] do
	  get 'new_from_github', :on => :collection
  end
	resources :users, 		:only => [:show, :new, :create, :edit, :update] do
		resources :posts, :only => :index
	end
  resources :posts do
		resources :comments, :except => [:index, :show, :new]
		get 'search', :on => :collection
	end
	resources :tags, :only => [:index, :show]
	
	namespace :admin do
		resources :users do
			put 'ban', :on => :member
		end
		resources :posts, :only => [:index, :destroy]
		resources :comments, :only => [:index, :edit, :update, :destroy]
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, 
									:publication_date, :published, :comments_disabled,
									:tags_attributes, :tag_tokens

	validates	:title,				:presence => :true,
													:length => {:within => 3..60}
	validates :content,			:presence => :true
	validates :user_id,			:presence => :true 
	validates :publication_date, :presence => :true
	
	belongs_to :user
	
	default_scope order('publication_date DESC').includes(:tags).includes(:user)
	scope :published, where(:published => true)
	
	has_many :comments, :dependent => :destroy
	has_many :tagments, :dependent => :destroy
	has_many :tags, :through => :tagments
	
	def to_param
		"#{id}-#{title.parameterize}"
	end
	
	def tag_tokens
		@tag_tokens = []
		self.tags.each do |tag|
			@tag_tokens << {:id => tag.id, :name => tag.name.humanize}
		end
		@tag_tokens
	end

	def tag_tokens=(ids)
		ids.gsub!(/CREATE_TAG_(.+?)_END/) do
		  Tag.create!(:name => $1.humanize).id
		end
		self.tag_ids = ids.split(",")
	end
end 

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  def index
		@posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
  end

  def destroy
		@post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_url, :notice => "Successfully destroyed post."
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :new_post, :only => [:new, :create]
	load_and_authorize_resource

  cache_sweeper :post_sweeper

  def index
		if params[:user_id]
			@posts = Post.accessible_by(current_ability).where(:user_id => params[:user_id]).paginate(:page => params[:page])
		else
			@posts = Post.accessible_by(current_ability).published.paginate(:page => params[:page], :per_page => 10)
		end
  end

	def search
		if params[:q]
			@posts = Post.accessible_by(current_ability).where('title LIKE :title', :title => "%#{params[:q]}%").paginate(:page => params[:page])
		else
			@posts = Post.accessible_by(current_ability).paginate(:page => params[:page])
		end
		render 'index'
	end

  def show
		@comments = @post.comments.includes(:user).order("created_at asc").paginate(:page => params[:page])
  end

  def new
		@post.publication_date = Time.zone.now
  end

  def create
		@post.update_attributes(params[:post])
    if @post.save
      redirect_to @post, :notice => "Successfully created post."
    else
      render :action => 'new'
    end
  end

  def edit
		store_referer
  end

  def update
    if @post.update_attributes(params[:post])
			flash[:notice] = "Successfully updated post."
      redirect_back_or @post
    else
      render :action => 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, :notice => "Successfully destroyed post."
  end

	private
		def new_post
			@post = current_user.posts.new
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f| 
	.fieldset
		= f.error_messages 
		.clearfix
			= f.label 'Title' 
			.input
				= f.text_field :title, :class => :xxlarge
				
		.clearfix
			= f.label "Content" 
			.input
				= f.text_area :content, :class => :xxlarge, :rows => 20
		
		.clearfix
			= f.label "Publication date"
			.input
				= f.text_field :publication_date, :id => 'datetimepicker'
				
		.clearfix
			= f.label "Tags"
			.input
				= f.text_field :tag_tokens, :id => 'tokeninput', 'data-pre' => @post.tag_tokens.to_json

		.clearfix
			= f.label "Options"
			.input
				%ul.inputs-list
					%li
						= hidden_field_tag "post[published]", ""
						%label
							= check_box_tag "post[published]", "true", @post.published?
							%span Published
					%li
						= hidden_field_tag "post[comments_disabled]", ""
						%label
							= check_box_tag "post[comments_disabled]", "true", @post.comments_disabled?
							%span Comments disabled
							
		.clearfix
			.input= f.submit :class => [:btn, :primary]

app/views/posts/_post.html.haml
.post
  .row
    = render :partial => 'posts/post_header', :locals => {:post => post}

  .row
    .span11.offset1
      - cache("post_#{post.id}_full_body", :expires_in => 1.day) do
        = markdown post.content
    
      - if can? :edit, post
        = link_to "Edit", edit_post_path(post)
        |
      = link_to "Back to index", posts_path

app/views/posts/_post_header.html.haml
.span1
	= gravatar_for(post.user)
.span11
	%h1= link_to post.title, post
	%small
		= "&mdash;".html_safe + " " + link_to("#{post.user.name.humanize}", user_path(post.user))
		|
		= post.publication_date < Time.current ? "#{time_ago_in_words post.publication_date} ago" : "#{time_ago_in_words post.publication_date} from now"
		- if post.tags.any?
			|
			- post.tags.each do |tag|
				%span.label.notice= link_to tag.name.humanize, tag
		- if can? :edit, post
			%span.subheading
				|
				= link_to "Edit", edit_post_path(post)
		- if can? :destroy, post
			%span.subheading
				|
				= link_to "Remove", post_path(post), :method => :delete, :confirm => "Are you sure you want to destroy this post?"

app/views/posts/_search_form.html.haml
= form_tag(search_posts_path, :method => 'get', :class => "pull-left") do
		= text_field_tag :q, params[:q], :placeholder => "Search posts"

app/views/posts/edit.html.haml
- title "Edit Post"

= render 'form'

%p
	= link_to "Show", @post
	| 
	= link_to "View All", posts_path

app/views/posts/index.html.haml
- title "Posts", false

- @posts.each do |post|
  .post
    .row
      = render :partial => 'post_header', :locals => {:post => post}

    .row
      .span11.offset1
        - cache("post_#{post.id}_short_body", :expires_in => 1.hour) do
          = markdown(truncate(post.content, :length => 1000, :separator => ' ')).html_safe
        = link_to("Read more", post)
        = " (#{post.comments.size} comments)"

= will_paginate @posts

- content_for(:sidebar) do
  - cache('taglist', :expires_in => 1.hour) do
    = render :partial => 'layouts/taglist'

app/views/posts/new.html.haml
- title "New Post"

= render 'form'

%p= link_to "Back to List", posts_path

app/views/posts/show.html.haml
- title @post.title, false

= render @post

- if can? :read, Comment
	- unless @post.comments.empty?
		%h1 Comments:
		=render @comments
		=will_paginate @comments

- if can? :create, Comment
	- unless @post.comments_disabled
		.row
			.span1
				= gravatar_for(current_user)
			.span9
				%strong New Comment:
				= render 'comments/form'
- else
	.row
		.span9.offset1.prepend-top.append-bottom
			= "You can #{link_to "sign in", new_from_github_sessions_path} using Github if you want to comment".html_safe