config/routes.rb
Webl::Application.routes.draw do
	

	root :to => 'posts#index'
	match '/about' => 'static#about'
	match '/signout' => 'sessions#destroy', :as => :sign_out
	match '/signin' => 'sessions#new', :as => :sign_in

  match "/auth/:provider/callback" => "sessions#create_from_github"
  match "/auth/failure" => "sessions#failure_from_github"
	resources :sessions, 	:only => [:new, :create, :destroy] do
	  get 'new_from_github', :on => :collection
  end
	resources :users, 		:only => [:show, :new, :create, :edit, :update] do
		resources :posts, :only => :index
	end
  resources :posts do
		resources :comments, :except => [:index, :show, :new]
		get 'search', :on => :collection
	end
	resources :tags, :only => [:index, :show]
	
	namespace :admin do
		resources :users do
			put 'ban', :on => :member
		end
		resources :posts, :only => [:index, :destroy]
		resources :comments, :only => [:index, :edit, :update, :destroy]
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
	attr_accessible :name, :email, :password, :password_confirmation, :roles, :as => :admin
	has_secure_password
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	ROLES = %w[admin author banned] # position in this list should NEVER change

	validates :name,  		:presence 	=> true,
												:length   	=> { :within => 4..20 },
												:uniqueness => { :case_sensitive => false }
	validates :email,			:presence		=> true,
	                      :unless     => Proc.new { |user| user.github_uid }
	validates :email,			:length			=> { :within => 6..60 },
												:uniqueness => { :case_sensitive => false },
												:format			=> { :with => email_regex },
												:unless     => Proc.new { |user| user.email.nil?}
	validates :password, 	:presence		=> true,
												:on					=> :create
												
	before_save :generate_salt
	before_destroy :update_authored_articles
	
	has_many :posts
	has_many :comments, :dependent => :destroy
	
	def to_param
		"#{id}-#{name.parameterize}"
	end
	
  def self.authenticate_with_cookie(id, cookie_salt)
		user = find_by_id(id)
		(user && user.cookie_hash == cookie_salt) ? user : nil
 	end
 	
 	def self.create_from_omniauth(omniauth)
 	  User.new.tap do |user|
      user.github_uid = omniauth["uid"]
      user.name = omniauth["info"]["nickname"]
      user.email = omniauth["info"]["email"]
      user.github_name = omniauth["info"]["name"]
      user.gravatar_token = omniauth["extra"]["raw_info"]["gravatar_id"] if omniauth["extra"] && omniauth["extra"]["raw_info"]
      user.password = BCrypt::Password.create("#{rand}--#{rand}") # random password for OAuth user
      user.save!
    end
 	end
	
	def roles=(roles)
		self.roles_mask = (roles & ROLES).map { |r| 2**(ROLES.index(r)) }.sum
	end

	def roles
		ROLES.reject do |r|
			((roles_mask || 0) & 2**ROLES.index(r)).zero?
		end
	end
	
	def has_role?(role)
	  roles.include?(role.to_s)
	end
	
	
	private
		def generate_salt
			if new_record? 
				self.cookie_hash = BCrypt::Password.create("#{Time.now.utc}--#{password_digest}--#{rand}")
			end
		end
		
		def update_authored_articles
			# This method takes all the authored articles and updates them to a special 'deleted' user
			# the special 'deleted' user is created if necessary
			# to make sure that nobody registeres this name to steal articles, the user status is set to banned just to be sure
			random_pass = "#{Time.now.utc}--#{rand}"
			deleted_author = User.find_or_create_by_name(:name => "Non existing user", :password => random_pass, :password_confirmation => random_pass, :email => APP_CONFIG[:deleted_user_email])
			deleted_author.roles = ['banned']
			deleted_author.save
			posts.each do |post|
				post.user = deleted_author
				post.save
			end
		end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
	load_resource :except => :index
	
  def index
		@users = User.order(:name).paginate(:page => params[:page])
  end

  def show
  end

  def new
  end

	def create
		@user.update_attributes(params[:user], :as => :admin)
		if @user.save
			sign_in @user
			flash[:success] = "New user added!"
			redirect_to admin_user_path @user
		else
			flash.now[:error] = "Oops! There was an error saving this user."
			render 'new'
		end
	end

  def edit
  end

	def update
		if @user.update_attributes(params[:user], :as => :admin)
			flash[:success] = "Profile updated."
			redirect_to admin_user_path @user
		else
			flash.now[:error] = "Oops! There was an error updating this profile."
			render 'edit'
		end
	end

  def destroy
		@user.destroy
		Rails.logger.debug @user.errors.messages
		redirect_to admin_users_path
  end

	def ban
		@user = User.find(params[:id])
		if @user.has_role? 'banned'
			@user.roles = @user.roles.reject {|r| r == 'banned'}
			flash[:notice] = "User #{@user.name} has been unbanned."
		else
			@user.roles += ['banned']
			flash[:notice] = "User #{@user.name} has been banned."
		end
		@user.save!
		redirect_to :back
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	
	def show
	end
	
	def new
	end
	
	def create
		if @user.save
			sign_in @user
			flash[:success] = "Registration Successful!"
			redirect_to @user
		else
			flash.now[:error] = "Oops! There was an error saving your profile."
			render 'new'
		end
	end

	def edit
	end
	
	def update
		params[:user].delete :name # don't allow username changes
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated."
			redirect_to @user
		else
			flash.now[:error] = "Oops! There was an error updating your profile."
			render 'edit'
		end
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50, :default => 'mm' })     
    if user.gravatar_token
      return gravatar_token_tag(user.gravatar_token, 
                  :size => options[:size], 
                  :title => user.name,
                  :class => 'gravatar',
                  :alt => user.name)
    else
      return gravatar_image_tag(user.email.downcase, 
                  :alt => user.name,
                  :title => user.name,
                  :class => 'gravatar',
                  :gravatar => options)
    end
  end
  
  def gravatar_token_tag(token, options)
	  size = options.delete :size || 50
	  image_tag "http://www.gravatar.com/avatar/#{token}.png?s=#{size}", :title => options[:title], :class => :gravatar
	end
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
	.fieldset
		.clearfix
			= f.error_messages
		.clearfix
			=f.label :name
			.input= f.text_field :name
		.clearfix
			=f.label :email
			.input= f.text_field :email
		.clearfix
			=f.label :password
			.input= f.password_field :password
		.clearfix
			=f.label :password_confirmation
			.input= f.password_field :password_confirmation
		.clearfix
			=f.label :roles
			.input
				%ul.inputs-list
					- User::ROLES.each do |role|
						%li
							%label
								= check_box_tag "user[roles][]", role, @user.roles.include?(role)
								%span= role.humanize
					= hidden_field_tag "user[roles][]", ""
		.clearfix
			.input= f.submit :class => [:btn, :primary]

app/views/admin/users/edit.html.haml
-title "Editing #{@user.name.humanize}"


= render :partial => 'form'

app/views/admin/users/index.html.haml
-title "User Index"

%table
	%tr
		%th
		%th Name
		%th E-mail
		%th
		%th
		%th
	-for user in @users
		%tr
			%td= gravatar_for(user)
			%td= link_to user.name, admin_user_path(user)
			%td= user.email
			%td= link_to "edit", edit_admin_user_path(user)
			- if user.has_role? 'banned'
				%td= link_to "unban", ban_admin_user_path(user), :method => :put, :confirm => "Are you sure you want to unban #{user.name}?"
			- else
				%td= link_to "ban", ban_admin_user_path(user), :method => :put, :confirm => "Are you sure you want to ban #{user.name}?"
			%td= link_to "destroy",  admin_user_path(user), :method => :delete, :confirm => "Are you sure you want to delete #{user.name}?"

= will_paginate @users

app/views/admin/users/new.html.haml
-title "New user"

= render :partial => 'form'

app/views/admin/users/show.html.haml
-title "#{@user.name.humanize}"

%h2 Personal details:

%p
	%strong E-mail:
	= @user.email

%p
	%strong Registration date:
	= @user.created_at

%p
	%strong Roles:
	= @user.roles.join(',')


%p
	= link_to 'edit', edit_admin_user_path(@user), :class => :btn
	- if @user.has_role? :banned
		= link_to "unban", ban_admin_user_path(@user), :method => :put, :confirm => "Are you sure you want to unban #{@user.name}?", :class => :btn
	- else
		= link_to "ban", ban_admin_user_path(@user), :method => :put, :confirm => "Are you sure you want to ban #{@user.name}?", :class => :btn		
	= link_to 'destroy', admin_user_path(@user), :method => :delete, :confirm => "Are you sure you want to delete #{@user.name}?", :class => :btn

%h2 Recent comments:

%br
- @user.comments.order(:created_at).each do |comment|
	.comment.box
		="In reply to post: #{comment.post.title}, #{time_ago_in_words comment.created_at} ago"
		%p
			= comment.content
		%span.quiet
			= link_to :edit, edit_admin_comment_path(comment)
			|
			= link_to :destroy, admin_comment_path(comment, :method => :delete, :confirm => "Are you sure you want to delete this comment?")