config/routes.rb
Webl::Application.routes.draw do
	

	root :to => 'posts#index'
	match '/about' => 'static#about'
	match '/signout' => 'sessions#destroy', :as => :sign_out
	match '/signin' => 'sessions#new', :as => :sign_in

  match "/auth/:provider/callback" => "sessions#create_from_github"
  match "/auth/failure" => "sessions#failure_from_github"
	resources :sessions, 	:only => [:new, :create, :destroy] do
	  get 'new_from_github', :on => :collection
  end
	resources :users, 		:only => [:show, :new, :create, :edit, :update] do
		resources :posts, :only => :index
	end
  resources :posts do
		resources :comments, :except => [:index, :show, :new]
		get 'search', :on => :collection
	end
	resources :tags, :only => [:index, :show]
	
	namespace :admin do
		resources :users do
			put 'ban', :on => :member
		end
		resources :posts, :only => [:index, :destroy]
		resources :comments, :only => [:index, :edit, :update, :destroy]
	end

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

	def recent_tags(limit = 5)
		Tag.order("created_at DESC").limit(limit)
	end
	
	def active_tags(limit = 5)
		Tagment.select("*, count('tag_id') as 'count'").includes(:tag).group(:tag_id).order('count(*) DESC').limit(limit)
	end
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '<%= APP_CONFIG[:google_analytics_id]%>']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

</script>

app/views/layouts/_footer.html.haml
.span4
	%h1 Resources
	%p 
		Without which I would never have got this up and running so fast.
		%ul
			%li= link_to "Ruby on Rails", "http://rubyonrails.org"
			%li= link_to "Railscasts", "http://www.railscasts.com", :title => "Easiest way to learn new stuff about Rails"
			%li= link_to "Twitter's Bootstrap", "http://twitter.github.com/bootstrap"
		

.span4
	%h1 GitHub
	%p 
		This source of this Rails application is available on 
		= link_to "GitHub.", "https://github.com/HectorMalot/WebL"
	%p
		Feel free to check it out and take it for a spin.
		
.span4
	%h1 About
	%p 
		I started WebL to learn Ruby on Rails. 
		By now, it has evolved into a basic weblog, which I use to jot down stuff I discover or think of in everyday life.

-# a fourth column can be used if you want.	
-#.span4
-#	%h1 About
-#	%p 
-#		I started WebL to learn Ruby on Rails. 
-#		By now, it has evolved into a basic weblog, which I use to jot down stuff I find or think in everyday life.

app/views/layouts/_menu.html.haml
#topbar.topbar{"data-dropdown" => "dropdown"}
	.topbar-inner
		.container
			%h3= link_to "WebL", root_path
			%ul.nav
				= menu_item "Home", root_path
				- if can? :create, Post
					= menu_item "New Post", new_post_path
				= menu_item "About", about_path
			%ul.nav.secondary-nav
				= render 'posts/search_form'
				- if can? :manage, :all
					%li.dropdown
						= link_to "Manage", "#", :class => "dropdown-toggle"
						%ul.dropdown-menu
							%li= link_to "Users", admin_users_path
							%li= link_to "Posts", admin_posts_path
							%li= link_to "Comments", admin_comments_path
				- if signed_in? 
					%li.dropdown
						= link_to current_user.name.humanize, "#", :class => "dropdown-toggle"
						%ul.dropdown-menu
							%li= link_to "Profile", user_path(current_user)
							- if can? :create, Post
								%li= link_to "My Posts", user_posts_path(current_user)
							%li.divider
							%li= link_to "Sign out", sign_out_path
				- else
					%li= link_to "Sign in", sign_in_path
					%li= link_to "Register", new_user_path

app/views/layouts/_taglist.html.haml
%h1 Tags:
%ul.taglist
	- active_tags(20).each do |tagment|
		%li= link_to "#{tagment.tag.name.humanize} (#{tagment.count})", tagment.tag

app/views/layouts/application.html.haml
!!!
%html

	%head
		%title
			WebL
			= " | #{yield(:title)}" unless yield(:title).blank?
		%meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
		= stylesheet_link_tag :application
		= javascript_include_tag :application
		= csrf_meta_tags
		= yield(:head)
		= render :partial => 'layouts/analytics'

	%body
		.wrapper
			.container.body
				= render :partial => 'layouts/menu'
			
				.row
					.span12
						- flash.each do |name, msg|
							= flash_div(name, msg)
				
						- if show_title?
							%h1= yield(:title)

						= yield
					
					.span4
						.sidebar
							= yield(:sidebar)
		.footer
			.container
				.row
					= render :partial => 'layouts/footer'